# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-21 18:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trustee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyrecord',
            name='trustee_city',
            field=models.CharField(max_length=50, null=True, verbose_name=b'Trustee: City'),
        ),
        migrations.AddField(
            model_name='propertyrecord',
            name='trustee_zipcode',
            field=models.CharField(max_length=50, null=True, verbose_name=b'Trustee: Zip'),
        ),
        migrations.AlterField(
            model_name='propertyrecord',
            name='bathrooms',
            field=models.FloatField(blank=True, null=True, verbose_name=b'Bath'),
        ),
        migrations.AlterField(
            model_name='propertyrecord',
            name='bedrooms',
            field=models.FloatField(blank=True, null=True, verbose_name=b'Bed'),
        ),
        migrations.AlterField(
            model_name='propertyrecord',
            name='is_zillow_processed',
            field=models.BooleanField(default=False, verbose_name=b'ZP?'),
        ),
    ]
