# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 23:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trustee', '0002_auto_20170121_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyrecord',
            name='projected_diff',
            field=models.FloatField(blank=True, null=True, verbose_name=b'PDiff'),
        ),
        migrations.AddField(
            model_name='propertyrecord',
            name='projected_equity',
            field=models.FloatField(blank=True, null=True, verbose_name=b'Projected Equity'),
        ),
        migrations.AddField(
            model_name='propertyrecord',
            name='projected_open',
            field=models.FloatField(blank=True, null=True, verbose_name=b'Projected Open'),
        ),
        migrations.AddField(
            model_name='propertyrecord',
            name='trustee_bid_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name=b'Trustee: Opening Bid DateTime'),
        ),
        migrations.AddField(
            model_name='propertyrecord',
            name='trustee_continued_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name=b'Trustee: Continued DateTime'),
        ),
        migrations.AlterField(
            model_name='propertyrecord',
            name='what_owner_loves',
            field=models.TextField(blank=True, null=True, verbose_name=b'What Owner Loves'),
        ),
    ]
